INSERT INTO "Beers" ("BeerID", "CategoryID", "BeerName", "ABV", "Description")
VALUES
(1, 1, 'Raspberry Sour', 5.2, 'A refreshing sour beer infused with juicy raspberries.'),
(2, 2, 'Hoppy Haze IPA', 6.8, 'A hazy IPA bursting with tropical hop flavors.'),
(3, 3, 'Rich Chocolate Stout', 8.5, 'A decadent stout with notes of chocolate and roasted malt.'),
(4, 4, 'Crisp Lager', 4.8, 'A clean and crisp lager with a subtle hop bitterness.'),
(5, 5, 'Amber Ale', 5.6, 'An amber-colored ale with a balanced malt and hop profile.'),
(6, 1, 'Tart Cherry Sour', 4.9, 'A tangy sour beer infused with tart cherries.'),
(7, 2, 'Citrus IPA', 7.2, 'An IPA bursting with bright citrus flavors and aromas.'),
(8, 3, 'Vanilla Porter', 6.0, 'A smooth porter with hints of vanilla and roasted malt.'),
(9, 4, 'Czech Pilsner', 5.0, 'A classic Czech-style pilsner with a clean and crisp taste.'),
(10, 5, 'Belgian Tripel', 9.2, 'A strong and complex Belgian ale with fruity esters and spice.'),
(11, 1, 'Passionfruit Sour', 4.7, 'A sour beer infused with tropical passionfruit for a tangy twist.'),
(12, 2, 'Resinous IPA', 7.5, 'An IPA showcasing resinous hop characteristics and a piney aroma.'),
(13, 3, 'Mocha Stout', 7.8, 'A rich and velvety stout with flavors of coffee and chocolate.'),
(14, 4, 'Vienna Lager', 5.4, 'A malty amber lager with a smooth and balanced profile.'),
(15, 5, 'English Pale Ale', 5.2, 'An easy-drinking pale ale with biscuity malt flavors and a subtle hop bitterness.'),
(16, 1, 'Peach Sour', 4.6, 'A refreshing sour beer infused with ripe peaches for a sweet and tart taste.'),
(17, 2, 'West Coast IPA', 7.0, 'A hop-forward IPA with citrus and piney flavors, reminiscent of the West Coast style.'),
(18, 3, 'Oatmeal Milk Stout', 6.3, 'A creamy and smooth stout brewed with oats and lactose for added sweetness.'),
(19, 4, 'Munich Dunkel', 5.5, 'A dark and malty lager with notes of caramel and toasted bread.'),
(20, 5, 'Belgian Witbier', 4.8, 'A light and refreshing wheat beer brewed with Belgian yeast and spices.'),
(21, 1, 'Blackberry Sour', 4.8, 'A tart sour beer infused with juicy blackberries for a burst of fruity flavor.'),
(22, 2, 'Double Dry-Hopped IPA', 8.3, 'An intensely hoppy IPA with double the dry-hopping for a bold and aromatic experience.'),
(23, 3, 'Coconut Chocolate Stout', 7.9, 'A rich and indulgent stout featuring the combination of creamy coconut and decadent chocolate.'),
(24, 4, 'Helles Bock', 6.7, 'A strong and malty lager with a smooth and slightly sweet character.'),
(25, 5, 'Irish Red Ale', 5.3, 'A copper-colored ale with a toasted malt profile and subtle caramel notes.'),
(26, 1, 'Gose with Lime', 4.5, 'A tangy and salty German-style gose beer with a refreshing hint of lime.'),
(27, 2, 'New England IPA', 6.5, 'A hazy and juicy IPA with tropical hop flavors and a smooth mouthfeel.'),
(28, 3, 'Imperial Stout', 10.0, 'A bold and robust stout with high alcohol content and rich flavors of dark chocolate and roasted malt.'),
(29, 4, 'Crisp Pilsner', 5.1, 'A crisp and clean pilsner with a slightly bitter hop finish and a light golden color.'),
(30, 5, 'American Pale Ale', 5.4, 'A balanced and refreshing pale ale with a moderate hop bitterness and citrusy hop flavors.'),
(31, 1, 'Blueberry Sour', 4.7, 'A sour beer infused with plump blueberries for a sweet and tangy flavor combination.'),
(32, 2, 'Session IPA', 4.8, 'An easy-drinking IPA with lower alcohol content, perfect for longer sessions of enjoyment.'),
(33, 3, 'Hazelnut Stout', 7.2, 'A rich and velvety stout with the warm nuttiness of hazelnuts and notes of chocolate.'),
(34, 4, 'Amber Lager', 5.3, 'A malt-forward lager with a reddish-amber color and a smooth, caramel-like sweetness.'),
(35, 5, 'Belgian Golden Ale', 7.8, 'A strong and complex Belgian ale with fruity esters, spicy phenols, and a dry finish.'),
(36, 1, 'Watermelon Sour', 4.4, 'A refreshing and tangy sour beer infused with juicy watermelon, perfect for summer.'),
(37, 2, 'West Coast Double IPA', 8.7, 'An intensely hoppy and bitter double IPA with a strong malt backbone and resinous hop flavors.'),
(38, 3, 'Irish Dry Stout', 4.2, 'A dark and dry stout with roasted malt flavors and a smooth, creamy mouthfeel.'),
(39, 4, 'Czech Dark Lager', 5.2, 'A traditional Czech-style dark lager with a malty profile and a clean, crisp finish.'),
(40, 5, 'American Amber Ale', 5.8, 'An amber-colored ale with a balanced blend of caramel malt sweetness and moderate hop bitterness.'),
(41, 1, 'Rhubarb Sour', 4.6, 'A tart and tangy sour beer infused with fresh rhubarb for a unique and refreshing flavor.'),
(42, 2, 'Juicy Double IPA', 9.2, 'A bold and juicy double IPA packed with tropical and citrus hop flavors and a strong malt backbone.'),
(43, 3, 'Mint Chocolate Stout', 7.5, 'A rich and indulgent stout brewed with cocoa nibs and infused with cool and refreshing mint.'),
(44, 4, 'Vienna Amber Lager', 5.4, 'An amber lager with a toasty malt character and a slightly sweet finish, showcasing Vienna malt.'),
(45, 5, 'English ESB', 5.6, 'An Extra Special Bitter with a balanced malt-hop profile and a fruity, earthy hop character.'),
(46, 1, 'Pineapple Sour', 4.8, 'A tropical sour beer infused with juicy pineapple for a tangy and refreshing flavor.'),
(47, 2, 'Hazy Session IPA', 4.5, 'A sessionable and hazy IPA bursting with tropical hop aromas and flavors.'),
(48, 3, 'Coffee Stout', 6.8, 'A robust stout brewed with coffee beans, offering rich coffee flavors and a velvety smooth texture.'),
(49, 4, 'Doppelbock', 8.0, 'A strong and malty German-style lager with a deep amber color and complex caramel malt flavors.'),
(50, 5, 'Belgian Tripel', 9.5, 'A strong and golden Belgian ale with fruity esters, spicy phenols, and a dry finish.'),
(51, 1, 'Apricot Sour', 4.5, 'A sour beer infused with ripe apricots, delivering a tart and fruity flavor experience.'),
(52, 2, 'Brut IPA', 7.1, 'A bone-dry IPA with a crisp and effervescent mouthfeel, featuring hop flavors that shine through.'),
(53, 3, 'Salted Caramel Stout', 7.7, 'A luscious stout with the perfect balance of roasted malt, caramel sweetness, and a touch of sea salt.'),
(54, 4, 'Märzen', 5.8, 'A traditional German lager with a rich malt profile and a smooth, clean finish, typically enjoyed during Oktoberfest.'),
(55, 5, 'Belgian Strong Dark Ale', 9.8, 'A complex and full-bodied Belgian ale with rich maltiness, dark fruit flavors, and spicy yeast notes.');