INSERT INTO "Events" ("EventID", "EventName", "Date", "Description")
VALUES
  (1, 'Brews & Beats Festival', '2023-07-01', 'Join us for a fantastic combination of live music performances and a wide selection of craft beers.'),
  (2, 'Oktoberfest Celebration', '2023-07-15', 'Experience the famous German beer festival with traditional music, delicious food, and an array of authentic Oktoberfest beers.'),
  (3, 'Hoppy Harmony Fest', '2023-07-22', 'Indulge in the harmonious blend of hoppy brews and live music at this beer lover''s paradise.'),
  (4, 'Craft Beer & Rock Festival', '2023-08-05', 'Rock out to electrifying live performances while sampling a diverse range of handcrafted beers from local breweries.'),
  (5, 'Sour Sounds & Pours', '2023-08-19', 'Immerse yourself in the world of sour beers accompanied by live music that perfectly complements their unique flavors.'),
  (6, 'IPA Jam Session', '2023-09-02', 'Discover the bold and hop-forward world of IPAs as you enjoy live jam sessions by talented musicians.'),
  (7, 'Beer & Blues Bash', '2023-09-16', 'Experience the soulful sounds of blues music while sipping on a variety of delicious beers from around the world.'),
  (8, 'Summer Beer Jamboree', '2023-09-30', 'Celebrate the summer season with a lively beer jamboree featuring a vast selection of refreshing brews and live music.'),
  (9, 'Lagerfest', '2023-10-14', 'Raise your glass and toast to the world of lagers at this festival showcasing a wide range of crisp and refreshing beer styles.'),
  (10, 'Funk & Brews Extravaganza', '2023-10-28', 'Get down to funky beats while sipping on a wide variety of brews at this exciting festival.'),
  (11, 'Cider & Sounds Festival', '2023-11-11', 'Enjoy the crisp and refreshing flavors of ciders while listening to a diverse lineup of musical performances.'),
  (12, 'Winter Beer Wonderland', '2023-11-25', 'Embrace the winter season with a magical beer wonderland featuring seasonal brews and live music.'),
  (13, 'Amber Ale Affair', '2023-12-09', 'Indulge in the rich and malty goodness of amber ales while soaking in the festive atmosphere and live entertainment.'),
  (14, 'Pilsner Palooza', '2024-01-13', 'Celebrate the classic and refreshing pilsner style with a palooza of flavors and live music performances.'),
  (15, 'Stout Spectacular', '2024-01-27', 'Delve into the world of dark and roasty stouts accompanied by captivating live music acts.'),
  (16, 'IPA Festivity', '2024-02-10', 'Immerse yourself in the hoppy festivities of India Pale Ales with a wide selection of IPAs and energetic live performances.'),
  (17, 'Summer Saison Soirée', '2024-02-24', 'Savor the refreshing and farmhouse-style saisons while enjoying a vibrant summer soirée with live music.'),
  (18, 'Barleywine Bonanza', '2024-03-09', 'Experience the bold and complex flavors of barleywines at this bonanza of rich brews and live music.'),
  (19, 'Hazy Hops Harmony', '2024-03-23', 'Discover the hazy and juicy world of hoppy beers with a harmonious blend of flavors and live musical talents.'),
  (20, 'Belgian Beer Bash', '2024-04-06', 'Transport yourself to Belgium as you indulge in a wide range of authentic Belgian beers and enjoy lively music.'),
  (21, 'Sour Beer Showcase', '2024-04-20', 'Explore the delightful world of sour beers with a showcase of unique and tangy brews accompanied by live music.'),
  (22, 'Porter Party', '2024-05-04', 'Join the porter party and relish in the smooth and roasted flavors of porters while enjoying live musical performances.'),
  (23, 'Fruit Beer Fiesta', '2024-05-18', 'Celebrate the vibrant and fruity flavors of fruit beers at this fiesta of refreshing brews and lively tunes.'),
  (24, 'Wheat Beer Whirlwind', '2024-06-01', 'Get swept away in a whirlwind of refreshing wheat beers and enjoy live music that perfectly complements their light and crisp nature.'),
  (25, 'Summer Solstice Sips', '2024-06-15', 'Toast to the summer solstice with a delightful selection of beers and enjoy live musical entertainment.'),
  (26, 'Hop Harvest Hootenanny', '2024-06-29', 'Celebrate the hop harvest season with a hootenanny of hoppy brews and live music performances.'),
  (27, 'Cask Ale Carnival', '2024-07-13', 'Experience the art of cask-conditioned ales at this carnival of traditional and unique beer offerings, complemented by lively music.'),
  (28, 'Märzen Madness', '2024-07-27', 'Join the madness of Märzen beers with their rich maltiness and enjoy live music that adds to the festive atmosphere.'),
  (29, 'Saison Symphony', '2024-08-10', 'Immerse yourself in a symphony of refreshing and spicy saisons, paired with a diverse range of musical talents.'),
  (30, 'Hoppy Hour Festival', '2024-08-24', 'Celebrate the magic of hoppy beers during this hoppy hour festival, featuring an extensive selection of hop-forward brews and live music.'),
  (31, 'Oktoberfest Revival', '2024-09-07', 'Revive the spirit of Oktoberfest with an authentic celebration of German beer, food, and music.'),
  (32, 'Barrel-aged Bonanza', '2024-09-21', 'Delight in the complex flavors of barrel-aged beers at this bonanza of unique brews and live music performances.'),
  (33, 'Harvest Ale Hoedown', '2024-10-05', 'Kick up your heels at the harvest ale hoedown, where you can enjoy flavorful brews and dance to lively tunes.'),
  (34, 'Winter Warmer Wonderland', '2024-10-19', 'Escape into a winter warmer wonderland with a selection of comforting and spiced beers, accompanied by live music.'),
  (35, 'Pumpkin Party', '2024-11-02', 'Get into the festive spirit with a pumpkin-themed beer party, featuring pumpkin ales and live music to keep the party going.'),
  (36, 'Funky Fermentation Fest', '2024-11-16', 'Discover the funky side of fermentation with a festival showcasing wild and sour beers, complemented by funky live tunes.'),
  (37, 'Holiday Cheer Celebration', '2024-11-30', 'Celebrate the holiday season with a cheer-filled festival of festive beers and joyful live music performances.'),
  (38, 'Winter Stout Showcase', '2024-12-14', 'Indulge in the richness of winter stouts at this showcase of robust and flavorful brews, accompanied by live music acts.'),
  (39, 'New Years Brew Bash', '2024-12-31', 'Ring in the new year with a brew bash featuring a wide array of beers, lively music, and a festive atmosphere.'),
  (40, 'Hoppy New Beginnings', '2025-01-15', 'Start the new year with hoppy beginnings by exploring a variety of hop-forward beers and enjoying live music performances.'),
   (41, 'Sour Summer Soiree', '2025-01-31', 'Sip on tangy and refreshing sour beers at this summer soiree while enjoying live music and a vibrant atmosphere.'),
  (42, 'Hoppy Haze Fest', '2025-02-14', 'Dive into the world of hoppy and hazy beers at this festival, featuring a wide selection of juicy brews and lively music.'),
  (43, 'Stout and Smores Social', '2025-02-28', 'Savor the combination of rich stouts and gooey smores at this social event, accompanied by live music performances.'),
  (44, 'Fruit Infusion Fair', '2025-03-14', 'Experience the flavors of fruit-infused beers at this fair, where you can sample a variety of fruity brews and enjoy live music.'),
  (45, 'IPA Invitational', '2025-03-28', 'Celebrate the hoppy goodness of IPAs at this invitational event, featuring a curated selection of exceptional IPAs and energetic music.'),
  (46, 'Belgian Beer Bonanza', '2025-04-11', 'Immerse yourself in the world of Belgian beers at this bonanza, showcasing a wide range of styles and accompanied by lively music.'),
  (47, 'Summer Saison Showcase', '2025-04-25', 'Discover the refreshing and vibrant flavors of saisons at this summer showcase, with a variety of saisons on tap and live music to set the mood.'),
  (48, 'Porter and Pints Party', '2025-05-09', 'Raise your pints to a party dedicated to porters, where you can enjoy the rich and velvety flavors of porters along with live music.'),
  (49, 'Hop Harvest Jam', '2025-05-23', 'Join the hop harvest jam and celebrate the season with fresh hop beers, lively music, and a vibrant atmosphere.'),
  (50, 'Amber Ale Adventure', '2025-06-06', 'Embark on an adventure of amber ales, exploring their caramel maltiness and balanced flavors, while enjoying live music performances.'),
  (51, 'Crisp Lager Fest', '2025-06-20', 'Celebrate the crisp and clean flavors of lagers at this festival, where you can sample a wide range of lagers and groove to live music.'),
  (52, 'Summer Solstice Suds', '2025-07-04', 'Toast to the summer solstice with an array of refreshing sudsy brews, live music, and a festive atmosphere.'),
  (53, 'IPA Extravaganza', '2025-07-18', 'Immerse yourself in the hoppy extravaganza of India Pale Ales, featuring a selection of hop-forward brews and live music acts.'),
  (54, 'Sour Sensation Soirée', '2025-08-01', 'Experience a sensation of sour beers at this soirée, where you can sample a variety of tangy brews while enjoying live music.'),
  (55, 'Oktoberfest in July', '2025-08-15', 'Transport yourself to Oktoberfest in July with a celebration of German beers, food, music, and all the festive traditions.'),
  (56, 'Hoppy Hour Happy Hour', '2025-08-29', 'Unwind with a hoppy hour happy hour, featuring a selection of hop-forward beers to enjoy during this lively and upbeat event.'),
  (57, 'Cider Celebration', '2025-09-12', 'Raise a glass to a cider celebration, exploring a variety of crisp and refreshing ciders alongside live music performances.'),
  (58, 'Pumpkin Patch Party', '2025-09-26', 'Embrace the autumn spirit with a pumpkin-themed party, featuring pumpkin beers, seasonal treats, and lively music.'),
  (59, 'Winter Warmers Wonderland', '2025-10-10', 'Step into a winter warmers wonderland, where you can indulge in rich and spiced brews while enjoying live music and a cozy atmosphere.'),
  (60, 'Festive Ale Fiesta', '2025-10-24', 'Join the festive ale fiesta, celebrating the season with a variety of flavorful and festive brews, live music, and a joyful atmosphere.'),
    (61, 'Hoppy Halloween Bash', '2025-11-07', 'Get into the Halloween spirit with a hoppy bash, featuring spooky brews, live music, and festive costumes.'),
  (62, 'Barrel-Aged Bonanza', '2025-11-21', 'Indulge in the complex and rich flavors of barrel-aged beers at this bonanza, accompanied by live music and a cozy atmosphere.'),
  (63, 'Winter Wonderland Brews', '2025-12-05', 'Immerse yourself in a winter wonderland of brews, featuring seasonal favorites and live music to keep you in high spirits.'),
  (64, 'Stoutsgiving', '2025-12-19', 'Celebrate Stoutsgiving with a selection of hearty and indulgent stouts, paired with live music and a festive ambiance.'),
  (65, 'New Year, New Brews', '2026-01-02', 'Toast to the new year with a lineup of new and exciting brews, accompanied by live music and a lively atmosphere.'),
  (66, 'Winter Warmer Fest', '2026-01-16', 'Warm up from the winter chill with a festival dedicated to winter warmers, featuring rich and spiced brews and live music acts.'),
  (67, 'IPA Palooza', '2026-01-30', 'Join the IPA palooza and experience a multitude of India Pale Ales, showcasing different hop profiles and accompanied by energetic music.'),
  (68, 'Sour Sunday Funday', '2026-02-13', 'Make Sundays more fun with a sour-themed event, where you can enjoy a variety of tangy brews and live music performances.'),
  (69, 'Craft Beer Carnival', '2026-02-27', 'Step right up and experience the craft beer carnival, featuring a diverse range of unique and flavorful brews, live music, and carnival games.'),
  (70, 'Märzen Madness', '2026-03-13', 'Get into the Märzen madness and celebrate this classic German style with a variety of malty and flavorful Märzen beers, accompanied by live music.'),
  (71, 'Hazy Daze Festival', '2026-03-27', 'Enter a hazy daze and indulge in the world of hazy beers, with a wide selection of juicy and hazy brews to enjoy alongside live music.'),
  (72, 'Bock and Roll Bash', '2026-04-10', 'Rock and roll with a bock bash, featuring the rich and malty flavors of bock beers, live music performances, and a lively atmosphere.'),
  (73, 'Citra Sensation Showcase', '2026-04-24', 'Experience the citrusy goodness of Citra hops at this sensation showcase, featuring beers highlighting the vibrant and fruity hop variety.'),
  (74, 'Spring Saison Spectacle', '2026-05-08', 'Celebrate the arrival of spring with a saison spectacle, showcasing a variety of refreshing and vibrant saisons alongside live music.'),
  (75, 'Barleywine Bonanza', '2026-05-22', 'Delve into the world of barleywines at this bonanza, where you can enjoy the robust and complex flavors of these high-alcohol brews, accompanied by live music.'),
  (76, 'IPA Fiesta', '2026-06-05', 'Join the IPA fiesta and celebrate the hop-forward brews, with an array of IPAs to tantalize your taste buds and energetic music to keep you grooving.'),
  (77, 'Summer Solstice Soiree', '2026-06-19', 'Welcome the summer solstice with a lively soiree, featuring a selection of refreshing summer beers, live music, and a vibrant atmosphere.'),
  (78, 'Sour Serenade', '2026-07-03', 'Embark on a sour serenade, where you can savor the tart and funky flavors of sour beers, accompanied by live music performances.'),
  (79, 'Pilsner Party', '2026-07-17', 'Raise a glass to the crisp and clean flavors of pilsners at this party, showcasing a variety of refreshing and classic pilsner brews alongside live music.'),
  (80, 'Belgian Bliss', '2026-07-31', 'Indulge in the Belgian bliss, with a selection of traditional and innovative Belgian-style beers to enjoy alongside live music and a lively ambiance.'),
  (81, 'Oktoberfest Extravaganza', '2026-08-14', 'Celebrate Oktoberfest with an extravagant event, featuring traditional German beers, live music, and a lively Bavarian atmosphere.'),
  (82, 'Harvest Hop Harvest', '2026-08-28', 'Join the harvest hop harvest, where you can enjoy fresh-hopped beers showcasing the vibrant flavors of freshly harvested hops, accompanied by live music.'),
  (83, 'Amber Ale Affair', '2026-09-11', 'Immerse yourself in an amber ale affair, exploring a variety of malt-forward and caramel-rich amber ales, accompanied by live music performances.'),
  (84, 'Fruit Beer Festival', '2026-09-25', 'Experience the fruity delights of a fruit beer festival, with a wide array of fruit-infused brews to enjoy alongside live music and a festive atmosphere.'),
  (85, 'Porter Palooza', '2026-10-09', 'Celebrate the rich and roasty flavors of porters at this palooza, featuring a diverse selection of velvety and complex porter brews, accompanied by live music.'),
  (86, 'Fall Harvest Fair', '2026-10-23', 'Embrace the fall season with a harvest fair, showcasing a variety of seasonal brews, live music performances, and autumn-themed activities.'),
  (87, 'Belgian Strong Ale Bash', '2026-11-06', 'Raise a glass to the bold and complex flavors of Belgian strong ales at this bash, accompanied by live music and a festive ambiance.'),
  (88, 'Winter Spiced Stout Soirée', '2026-11-20', 'Indulge in a winter spiced stout soirée, featuring a selection of spiced and decadent stouts, live music, and a cozy atmosphere.'),
  (89, 'IPA Showcase', '2026-12-04', 'Experience the diversity of IPAs at this showcase, with a wide range of hop profiles and styles to enjoy alongside energetic music performances.'),
  (90, 'Holiday Ale Celebration', '2026-12-18', 'Celebrate the holiday season with an ale celebration, featuring a variety of festive and warming brews, live music, and a joyful atmosphere.'),
  (91, 'New Year Brews', '2027-01-01', 'Ring in the new year with a selection of exciting and innovative brews, accompanied by live music and a vibrant atmosphere.'),
  (92, 'Winter IPA Wonderland', '2027-01-15', 'Step into a winter IPA wonderland, where you can explore a variety of hoppy and bold IPAs while enjoying live music and a lively ambiance.'),
  (93, 'Sour Sensation Soiree', '2027-01-29', 'Embark on a sour sensation soiree, with an assortment of tangy and funky brews to delight your taste buds, accompanied by live music performances.'),
  (94, 'Stout and Chocolate Pairing', '2027-02-12', 'Indulge in a stout and chocolate pairing event, where you can savor the harmonious combination of rich stouts and decadent chocolates, accompanied by live music.'),
  (95, 'Festival of Farmhouse Ales', '2027-02-26', 'Celebrate the rustic and farmhouse-style brews at this festival, featuring a variety of refreshing and complex ales, live music, and a laid-back atmosphere.'),
  (96, 'Hazy IPA Hype', '2027-03-12', 'Experience the hazy IPA hype, with a selection of juicy and aromatic hazy IPAs to enjoy alongside energetic music performances and a vibrant ambiance.'),
  (97, 'Spring Saison Showcase', '2027-03-26', 'Welcome the arrival of spring with a saison showcase, featuring a variety of refreshing and vibrant saisons, accompanied by live music and a festive atmosphere.'),
  (98, 'Barrel-Aged Bonanza', '2027-04-09', 'Immerse yourself in a barrel-aged bonanza, exploring a diverse selection of beers aged in oak barrels to develop unique flavors, accompanied by live music.'),
  (99, 'Bock and Bratwurst Fest', '2027-04-23', 'Raise a stein to the traditional pairing of bock beers and bratwursts at this festive event, featuring live music and a lively German-inspired atmosphere.'),
  (100, 'Summer Session Sippers', '2027-05-07', 'Enjoy the sessionable beers of summer at this event, featuring a variety of light and refreshing brews, live music, and a laid-back summer vibe.');